### PR TITLE
Волхов Михаил 2538

### PR DESCRIPTION
**Pull request by volhovm**
1. It works
2. It passes all the tests
3. ???
4. GUI is ok too.

### CODE REVIEW

**Comment by thevery** [comment]
ooh, scala

**Comment by Nafanya** [comment]
Scala is every champion's choice

**Comment by pva701** [comment]
If keyboard was a piano keys and Scala code was music notes, this would be the greatest you have ever listened to!

**Comment by thevery** [comment]
There is no way you can sell scala to the groovy fan!

**Comment by volhovm** [comment]
What should I do now? The build seems to fail, but that's kind of strange, i haven't seen this error before. Maybe something specific about the build environment?

**Comment by thevery** [comment]
Scala cannot even compile on build server with 1GB RAM without swap. We'll check it on our laptops.

**Comment by volhovm** [comment]
Ok. After all, i've built it on mine.
http://pastebin.com/dq8KzDbc

**Comment by thevery** [comment]
ru.ifmo.md.lesson4.tests.AcceptanceTests > testInvalidExpression5 FAILED
    junit.framework.AssertionFailedError at AcceptanceTests.java:24

ru.ifmo.md.lesson4.tests.AcceptanceTests > testInvalidExpression7 FAILED
    junit.framework.AssertionFailedError at AcceptanceTests.java:24

ru.ifmo.md.lesson4.tests.AcceptanceTests > testInvalidExpression8 FAILED
    junit.framework.AssertionFailedError at AcceptanceTests.java:24

22 tests completed, 3 failed

**Comment by volhovm** [comment]
Should I fix it or what?

**Comment by svasilinets** [comment]
8 - 3 = 5.

**Pull request closed without merging**
